services:
  mongodb:
    image: mongo:7
    restart: unless-stopped
    ports:
      - "27018:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_ROOT_NAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_ROOT_PASSWORD}
    volumes:
      - dev_mongo_data:/data/db
      - ../../../mongo/init/dev:/docker-entrypoint-initdb.d
    networks:
      - team-work
      - dbs
    healthcheck:
      test: [ "CMD", "mongosh", "--eval", "db.adminCommand('ping')" ]
      interval: 5s
      timeout: 3s
      retries: 10
      start_period: 10s
  mysql:
    image: mysql:8.0
    networks:
      - team-work
      - dbs
    ports:
      - "3307:3306"
    volumes:
      - dev_mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 5s
      timeout: 3s
      retries: 10
  phpmyadmin:
    image: phpmyadmin:5.2.3-apache
    restart: unless-stopped
    ports:
      - "8031:80"
    networks:
      - dbs
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    depends_on:
      - mysql
  redis:
    image: redis:8.4-alpine
    networks:
      - dbs
      - team-work
    ports:
      - "6380:6379"
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "password", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3

  teamwork-app:
    image: mordiniaa/teamworkmon
    networks:
      - team-work
    depends_on:
      mongodb:
        condition: service_healthy
      mysql:
          condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
      - ./admin_password.txt:/run/secrets/admin_password:ro
      - dev_files_storage:${STORAGE_ROOT}
      - dev_profile_images_storage:${PROFILE_IMAGES_ROOT}
    ports:
      - "8081:8080"
    environment:
      PROFILE: dev
      STORAGE_ROOT: ${STORAGE_ROOT}
      PROFILE_IMAGES_ROOT: ${PROFILE_IMAGES_ROOT}
      MONGO_HOST: mongodb
      MONGO_PORT: 27017
      MONGO_DB_NAME: ${MONGO_DB_NAME}
      MONGO_DB_USERNAME: ${MONGO_DB_USERNAME}
      MONGODB_PASSWORD: ${MONGODB_PASSWORD}
      MYSQL_HOST: mysql
      MYSQL_DB_PORT: 3306
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    restart: unless-stopped

networks:
  team-work:
    driver: bridge
  dbs:
    driver: bridge

volumes:
  dev_mongo_data:
  dev_mysql_data:
  dev_files_storage:
  dev_profile_images_storage: