spring:
  application:
    name: backend
  output:
    ansi:
      enabled: always
  data:
    redis:
      host: localhost
      port: 6381
      jedis:
        pool:
          enabled: true
          max-active: 10
          max-idle: 5
          min-idle: 1
          max-wait: 3s
      username: redis-tester
      password: password
    mongodb:
      host: localhost
      port: 27019
      database: team-work
      username: team-work-tester
      password: password
      authentication-database: team-work
  datasource:
    url: jdbc:mysql://localhost:3308/team-work
    username: team-work-tester
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    database: mysql
  servlet:
    multipart:
      max-file-size: -1
      max-request-size: -1
  flyway:
    user: team-work-tester
    password: password
    url: jdbc:mysql://localhost:3308/team-work
    locations: classpath:db/migration
    schemas: team-work
  main:
    banner-mode: off

logging:
  level:
    org:
      springframework:
        security: trace
        boot:
          autoconfigure:
            data:
              redis: debug
storage:
  profileImages:
    path: ./profile_images_storage
    mimeTypes:
      - image/jpeg
      - image/png
    profileWidth: 512
    profileHeight: 512
    defaultImageKey: defaultProfileImage
    defaultImagePath: static/images/defaultProfileImage.png
  cloudStorage:
    path: ./files_storage

security:
  app:
    jwt:
      token-name: TEAMWORK-ACCESS
      issuer: teamwork-backend
      audience: teamwork-frontend
      secret: testSecret1dkWhat1@mwr1t1ngDrinkMilkBeHealthy
      minutes-of-life: 15
    refresh-token:
      token-name: TEAMWORK-REFRESH
      validity-days: 30
    refresh-token-family:
      max-session-days: 90