spring:
  application:
    name: backend
  data:
    mongodb:
      host: ${MONGO_HOST:localhost}
      port: ${MONGO_PORT:27017}
      database: ${MONGO_DB_NAME:team-work-temp}
      username: ${MONGO_DB_USERNAME:team-work-temp}
      password: ${MONGODB_PASSWORD:secretPass}
      authentication-database: ${MONGO_DB_NAME:team-work-temp}
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_DB_PORT:3306}/${MYSQL_DATABASE:team-work-temp}
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    database: mysql
  sql:
    init:
      mode: always
  servlet:
    multipart:
      max-file-size: -1
      max-request-size: -1

storage:
  profileImages:
    path: ${PROFILE_IMAGES_ROOT:./profile_images_storage}
    mimeTypes:
      - image/jpeg
      - image/png
    profileWidth: 512
    profileHeight: 512
    defaultImageKey: defaultProfileImage
    defaultImagePath: static/images/defaultProfileImage.png
  cloudStorage:
    path: ${STORAGE_ROOT:./files_storage}