spring:
  data:
    mongodb:
      host: ${TEST_MONGO_HOST}
      port: ${TEST_MONGO_PORT}
      database: ${TEST_DB_NAME}
      username: ${TEST_DB_USERNAME}
      password: ${TEST_MONGODB_PASSWORD}
      authentication-database: ${TEST_DB_NAME}
  h2:
    console:
      enabled: true
  datasource:
    url: ${TEST_DB_URL}
    username: ${TEST_DB_USERNAME}
    password: ${TEST_DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    database: ${TEST_DB_TYPE}